# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodePush' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'ZIPFoundation', '~> 0.9'
  pod 'React-Core'
  pod 'JWT', '~> 3.0.0-beta.12'
  pod 'Base64', '~> 1.1'
  use_frameworks!

  # Pods for CodePush

end

target 'CodePush-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodePush-tvOS

end
